export default [
  {
    id: 1,
    name: "Apple",
    price: 6,
    category: ["fruit"],
    image: "./apple.png",
  },
  {
    id: 2,
    name: "Carrot",
    price: 8,
    category: ["veggie"],
    image: "./carrot.png",
  },
  {
    id: 3,
    name: "Cauli Flower",
    price: 10,
    category: ["veggie"],
    image: "./cauli_flower.png",
  },
  {
    id: 4,
    name: "Lattuce",
    price: 10,
    category: ["veggie"],
    image: "./lattuce.png",
  },
  {
    id: 5,
    name: "Tomato",
    price: 5,
    category: ["veggie"],
    image: "./tomato.png",
  },
  {
    id: 6,
    name: "Raw Chicken",
    price: 12,
    category: ["meat"],
    image: "./chicken_breast.png",
  },
  {
    id: 7,
    name: "Raw Bacon",
    price: 20,
    category: ["meat"],
    image: "./raw_bacon.png",
  },
  {
    id: 8,
    name: "Beef",
    price: 22,
    category: ["meat"],
    image: "./raw_beef.png",
  },
  {
    id: 9,
    name: "Salmon",
    price: 35,
    category: ["fish"],
    image: "./salmon.png",
  },
  {
    id: 10,
    name: "Dragon Fruit",
    price: 10,
    category: ["fruit"],
    image: "./dragon_fruit.png",
  },
  {
    id: 11,
    name: "Red Bull Drink",
    price: 9,
    category: ["drink"],
    image: "./redbull.png",
  },
  {
    id: 12,
    name: "Monster Energy Drink",
    price: 9,
    category: ["drink"],
    image: "./monster_drink.png",
  },
  {
    id: 13,
    name: "Coca Cola",
    price: 5,
    category: ["drink"],
    image: "./cocacola.png",
  },
];
